# Generated by Django 3.2.5 on 2023-02-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sal',
            new_name='salary',
        ),
    ]
